spring.datasource.url=jdbc:postgresql://localhost:5432/clubapp
spring.datasource.username=postgres
spring.datasource.password=postgres
logging.level.org.springframework.security=DEBUG
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true

jwt.secret=0KnRHPD9cxZoilxNEzCZKd1armzi6vfp38GzuvZl03Wncxh6WIUYFr45FLGEfryFj4vk8NcjHDnqFVzlJ4cm9C
jwt.expiration=3600000
jwt.refreshExpiration=7200000

server.address=0.0.0.0
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=578hgbyu?
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=clubapp

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=helpteam@clubapp.com
spring.mail.password=testpassword
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
app.frontend.url=https://localhost:4200
app.frontend.base-url=https://localhost:8443